name: "Tests"

on:
  - push
  - pull_request

env:
    fail-fast: true

permissions:
    contents: read

jobs:
    unit-tests:
        name: "Unit tests"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.1', '8.2', '8.3']

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring
                  tools: composer:v2

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: "Cache composer"
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: "Composer install"
              run: composer install --prefer-dist --no-interaction --no-progress

            - name: "Launch unit tests"
              run: vendor/bin/phpunit
